### ISSUE TITLE
Bot can't read the token

### ISSUE THREAD

**Issue by Cinabon-bonn** [Bon-bonn/LeCroissant#3]
I have a problem with token. I mean, I tried to paste it in format "%someToken%", but it can't read I think

**Comment by Bon-bonn** [comment]
You're right. The bot just can't read token. So, try to paste token with this format "SomeToken" and don't forget about "()". So the full sentence is: TeleBot("PastHereToken");

**Comment by Cinabon-bonn** [comment]
Thanks!
